message("*beep boop* loading packages...")
suppressMessages(library(tidyverse))
suppressMessages(library(vroom))
suppressMessages(library(janitor))
suppressMessages(library(glue))
suppressMessages(library(RColorBrewer))
# suppressMessages(library(lme4))
suppressMessages(library(lmerTest))
suppressMessages(library(lattice))
suppressMessages(library(geepack))
message("*beep boop* packages loaded!!")